## Data preprocessing

In [1]:
import pandas as pd

# Load the dataset
df = pd.read_excel('qwen3_8b_train_results.xlsx')
df.head()

,index,STORY,QUESTION,OPTION-A,OPTION-B,OPTION-C,OPTION-D,ANSWER,SOURCE_FILE,qwen3_8b_full_response,qwen3_8b_reasoning,qwen3_8b_response,qwen3_8b_truncation,qwen3_8b_prompt_tokens,qwen3_8b_output_tokens
0,0,"In the supermarket, there are originally 60 bo...",Please guess how many bottles of soda are left...,"Before Manager Li counts, he guesses there are...","Before Manager Li counts, he guesses there are...","Before Manager Li counts, he guesses there are...","Before Manager Li counts, he guesses there are...",B,Scalar Implicature Test,"\n\nOkay, let's try to figure this out. So the...","Okay, let's try to figure this out. So the sto...",NaN,True,398,2048
1,1,Han Meimei and Youyou roam around in the bedro...,"After Youyou returns to the bedroom, where doe...",Briefcase,Cabinet,Box,Storage locker,B,False Belief Task,\n\n[Answer Options]\nA. Briefcase B. Cabinet ...,"Okay, let's break this down. The story says th...",B,False,317,415
2,2,Huang wants to sell his shop in the city cente...,How does Huang convince Wang?,"He shares his story with the shop, arousing Wa...","He shows the shop's turnover and profit, provi...",He suggests that life in the countryside is mo...,"He proposes to invest together with Wang, shar...",B,Persuasion Story Task,"\n\n[Step-by-Step Reasoning]\nFirst, the stor...","[Step-by-Step Reasoning]\nFirst, the story say...",B,True,351,2048
3,3,"On the weekend, Xiao Ming and Xiao Gang are on...",What happens to Xiao Gang's family recently?,Xiao Gang's dad changes his job.,Xiao Gang moves house.,Xiao Gang's mom is sick.,Xiao Gang fails the exam.,C,Faux-pas Recognition Test,"\n\nStep-by-step reasoning:\n\nFirst, let's a...","Step-by-step reasoning:\n\nFirst, let's analyz...",C,True,356,2048
4,4,"Zhang San is an engineer in the company, he wo...",How does Zhang San persuade Li Si?,Zhang San can emphasize how much effort he put...,Zhang San can present successful cases of simi...,Zhang San can persuade Li Si through other col...,Zhang San can invite Li Si to participate in a...,B,Persuasion Story Task,"\n\n[Reasoning Process]\nFirst, the story men...","[Reasoning Process]\nFirst, the story mentions...",B,True,381,2048

In [5]:
excel_file = pd.ExcelFile('qwen3_8b_train_results.xlsx')
sheet_names = excel_file.sheet_names
print(f"Sheet names in the Excel file: {sheet_names}")

# Load the second sheet
df_sheet2 = pd.read_excel('qwen3_8b_train_results.xlsx', sheet_name=sheet_names[1])
print(f"\nSecond sheet preview:")
df_sheet2.head()

Sheet names in the Excel file: ['1-1335', '1336-2002']

Second sheet preview:

,Unnamed: 0,index,STORY,QUESTION,OPTION-A,OPTION-B,OPTION-C,OPTION-D,ANSWER,SOURCE_FILE,qwen3_8b_full_response,qwen3_8b_reasoning,qwen3_8b_response,qwen3_8b_truncation,qwen3_8b_prompt_tokens,qwen3_8b_output_tokens
0,1336,1336,A science male student goes to a classroom to ...,What does she really want to say when the girl...,She indicates that she wants to go home and as...,She hopes the boy understands that she needs t...,She does not want to be with the boy.,She implies that she agrees with the boy's con...,D,Hinting Task Test,"\n\nOkay, let's try to figure out what the gi...","Okay, let's try to figure out what the girl re...",C,True,422,2048
1,1337,1337,"In school, Xiao Zhao meets Xiao Wang. Xiao Wan...",Does Xiao Zhao still remember the comic book t...,Knows,Does not know,NaN,NaN,A,Faux-pas Recognition Test,(Note: The original question may have had a t...,(Note: The original question may have had a ty...,A,True,373,2048
2,1338,1338,"On Saturday night, Xiao Min takes her boyfrien...",Does anyone say something inappropriate in thi...,Someone in the story says something inappropri...,No one in the story says anything inappropriate.,NaN,NaN,B,Faux-pas Recognition Test,(Note: The original question has four options...,"(Note: The original question has four options,...",B,False,394,293
3,1339,1339,"Xiao Zhang and Xiao Wang are colleagues, they ...",Does anyone say something inappropriate in thi...,Someone in the story says something inappropri...,No one in the story says anything inappropriate.,NaN,NaN,B,Faux-pas Recognition Test,(Note: The original question has four options...,"(Note: The original question has four options,...",B,False,377,293
4,1340,1340,"Retired old man, Mr. Li, hopes to hold a cultu...",How does Li convince the residents?,Li can emphasize that there are foods from dif...,Combine the cultural evening with charity acti...,Li's positive attitude possibly infects commun...,Emphasize that this activity is an opportunity...,A,Persuasion Story Task,"\n\nOkay, let's see. The story is about Mr. L...","Okay, let's see. The story is about Mr. Li, a ...",D,True,379,2048

In [6]:
# Combine the two sheets into one dataframe
df_combined = pd.concat([df, df_sheet2], ignore_index=True)
print(f"Combined dataframe shape: {df_combined.shape}")
df_combined.head()

Combined dataframe shape: (2003, 16)

,index,STORY,QUESTION,OPTION-A,OPTION-B,OPTION-C,OPTION-D,ANSWER,SOURCE_FILE,qwen3_8b_full_response,qwen3_8b_reasoning,qwen3_8b_response,qwen3_8b_truncation,qwen3_8b_prompt_tokens,qwen3_8b_output_tokens,Unnamed: 0
0,0,"In the supermarket, there are originally 60 bo...",Please guess how many bottles of soda are left...,"Before Manager Li counts, he guesses there are...","Before Manager Li counts, he guesses there are...","Before Manager Li counts, he guesses there are...","Before Manager Li counts, he guesses there are...",B,Scalar Implicature Test,"\n\nOkay, let's try to figure this out. So the...","Okay, let's try to figure this out. So the sto...",NaN,True,398,2048,NaN
1,1,Han Meimei and Youyou roam around in the bedro...,"After Youyou returns to the bedroom, where doe...",Briefcase,Cabinet,Box,Storage locker,B,False Belief Task,\n\n[Answer Options]\nA. Briefcase B. Cabinet ...,"Okay, let's break this down. The story says th...",B,False,317,415,NaN
2,2,Huang wants to sell his shop in the city cente...,How does Huang convince Wang?,"He shares his story with the shop, arousing Wa...","He shows the shop's turnover and profit, provi...",He suggests that life in the countryside is mo...,"He proposes to invest together with Wang, shar...",B,Persuasion Story Task,"\n\n[Step-by-Step Reasoning]\nFirst, the stor...","[Step-by-Step Reasoning]\nFirst, the story say...",B,True,351,2048,NaN
3,3,"On the weekend, Xiao Ming and Xiao Gang are on...",What happens to Xiao Gang's family recently?,Xiao Gang's dad changes his job.,Xiao Gang moves house.,Xiao Gang's mom is sick.,Xiao Gang fails the exam.,C,Faux-pas Recognition Test,"\n\nStep-by-step reasoning:\n\nFirst, let's a...","Step-by-step reasoning:\n\nFirst, let's analyz...",C,True,356,2048,NaN
4,4,"Zhang San is an engineer in the company, he wo...",How does Zhang San persuade Li Si?,Zhang San can emphasize how much effort he put...,Zhang San can present successful cases of simi...,Zhang San can persuade Li Si through other col...,Zhang San can invite Li Si to participate in a...,B,Persuasion Story Task,"\n\n[Reasoning Process]\nFirst, the story men...","[Reasoning Process]\nFirst, the story mentions...",B,True,381,2048,NaN

In [9]:
# Check the total number of records
total_records = len(df_combined)
print(f"Total number of records: {total_records}")

Total number of records: 2003

In [10]:
# Filter rows where qwen3_8b_reasoning starts with '('
starts_with_paren = df_combined['qwen3_8b_reasoning'].str.startswith('(')
count_starts_with_paren = starts_with_paren.sum()
print(f"Number of rows where qwen3_8b_reasoning starts with '(': {count_starts_with_paren}")

Number of rows where qwen3_8b_reasoning starts with '(': 119

In [14]:
# Display all rows where qwen3_8b_reasoning starts with '('
rows_starting_with_paren = df_combined[starts_with_paren]
print(f"Rows where qwen3_8b_reasoning starts with '(':\n")
print(rows_starting_with_paren[[ 'qwen3_8b_reasoning']])

Rows where qwen3_8b_reasoning starts with '(':

                                     qwen3_8b_reasoning
70    (Note: The original question has four options,...
345   (Note: The original question may have had a ty...
411   (Note: The original question may have had a ty...
712   (Note: The original question may have had a ty...
727   (Note: The options C and D are not provided, b...
...                                                 ...
1985  (Note: The original question may have had more...
1994  (Note: The original question had options A to ...
1995  (Note: The original question has four options,...
1996  (Note: The original question may have had a ty...
2000  (Note: The original question may have had a ty...

[119 rows x 1 columns]

In [15]:
# Remove lines starting with "(Note:" from qwen3_8b_reasoning column
df_combined['qwen3_8b_reasoning'] = df_combined['qwen3_8b_reasoning'].str.replace(
    r'\(Note:.*?\)', '', regex=True
).str.strip()

print(f"Updated qwen3_8b_reasoning column")
df_combined[['qwen3_8b_reasoning']].head()

Updated qwen3_8b_reasoning column

                                  qwen3_8b_reasoning
0  Okay, let's try to figure this out. So the sto...
1  Okay, let's break this down. The story says th...
2  [Step-by-Step Reasoning]\nFirst, the story say...
3  Step-by-step reasoning:\n\nFirst, let's analyz...
4  [Reasoning Process]\nFirst, the story mentions...

In [17]:
# check again
# Filter rows where qwen3_8b_reasoning starts with '('
starts_with_paren_new = df_combined['qwen3_8b_reasoning'].str.startswith('(')
count_starts_with_paren_new = starts_with_paren_new.sum()
print(f"Number of rows where qwen3_8b_reasoning starts with '(': {count_starts_with_paren_new}")

Number of rows where qwen3_8b_reasoning starts with '(': 1

In [18]:
# Display all rows where qwen3_8b_reasoning starts with '('
rows_starting_with_paren_new = df_combined[starts_with_paren_new]
print(f"Rows where qwen3_8b_reasoning starts with '(':\n")
print(rows_starting_with_paren_new[[ 'qwen3_8b_reasoning']])

Rows where qwen3_8b_reasoning starts with '(':

                                   qwen3_8b_reasoning
70  (Note: The original question has four options,...

## Check the total number of failure cases

In [19]:
# Count the number of rows where ANSWER matches qwen3_8b_response
matching_rows = (df_combined['ANSWER'] == df_combined['qwen3_8b_response']).sum()
print(f"Number of rows where ANSWER matches qwen3_8b_response: {matching_rows}")

Number of rows where ANSWER matches qwen3_8b_response: 1370

In [20]:
# Filter rows where ANSWER does not match qwen3_8b_response
non_matching_rows = df_combined[df_combined['ANSWER'] != df_combined['qwen3_8b_response']]

# Save to CSV
non_matching_rows.to_csv('qwen3_8b_failure_cases.csv', index=False)

print(f"Number of failure cases (non-matching rows): {len(non_matching_rows)}")
print(f"Saved to 'qwen3_8b_failure_cases.csv'")

Number of failure cases (non-matching rows): 633
Saved to 'qwen3_8b_failure_cases.csv'